FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

EXPOSE 8080

CMD ["streamlit", "run" ,"main:app", "--server.port", "8080", "--server.address=0.0.0.0"]
